import javax.swing.JOptionPane;
import java.awt.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Soal extends javax.swing.JFrame {

    String Nama ="";
    int noSoal = 1;
    int noJawaban = 0;
    String jawaban ="";
    int Benar = 0;
    int Salah = 0;
    
    String Soal[][]={
            {" ... Merupakan daerah di Jakarta dengan jumlah penduduk terbanyak.",  " Jakarta Utara", " Jakata Selatan"," Jakarta Barat", " Jakarta Timur",},
            {" ... Merupakan daerah di Jakarta dengan jumlah penduduk terbanyak.",  " Jakarta Utara", " Jakata Selatan"," Jakarta Barat", " Jakarta Timur",},
            {" Terdapat sebuah larangan pada kawasan Gili Trawangan. Larangan tersebut adalah...", " Larangan kendaraan listrik"," Larangan berjalan kaki",  " Larangan berkuda"," Larangan kendaraan bermotor",},
            {" Lapas yang terkenal di Jawa Tengah adalah..."," Sukamiskin", " Cipinang"," Nusakambangan", " Cianjur",},
            {" Angkot di Makassar dikenal dengan sebutan.."," Pete-pete",  " Pitu-pitu",  " Piti-piti", " Peta-peta",},
            {" Debus adalah kesenian tradisional Banten. Fungsi awal dari debus adalah..."," Untuk menguasai Pulau Jawa", " Untuk mengelabui penjajah", " Sarana penyebaran agama islam", " Memikat lawan jenis",},
            {" Menurut data BPS 2021, Aceh adalah provinsi dengan persentase penduduk... tertinggi di pulau Sumatera"," Kaya"," Miskin"," Paling sering keluar negeri"," Bahagia",},
            {" Tokoh yang ada di pecahan uang Rp20.000,00 TE 2022 adalah...","A. Ir. H. Djuanda Kartawidjaja", "B. Dr. K.H Idham Chalid","C. Dr. G.S.S.J. Ratulangi", " Mohammad Hoesni Thamrin",},
            {" Badik Tumbuk Lado adalah senjata tradisional Kepulauan Riau. Ciri Khas badik asal Kepri yaitu, bilah bedik diberi..."," Darah"," Racun", " Minyak"," Getah",},
            {" Berikut ini merupakan julukan-julukan Kota Semarang kecuali.."," Venetie van Java", " Port of Java", " Kota Atlas"," Delhi van Java",},
            {" Dimanakah letak Kawasan Wisata Kota Tua...", " Jakarta Pusat", " Jakarta Timur", " Jakarta Selatan", " Jakarta Barat",}
    };
    String Jawaban[]={" Jakarta Barat"," Larangan kendaraan bermotor"," Nusakambangan"," Pete-pete"," Sarana penyebaran agama islam"," Miskin"," Dr. G.S.S.J. Ratulangi"," Racun"," Delhi van Java"," Jakarta Barat",};
    //                Jawaban[0], Jawaban[1], Jawaban[2], Jawaban[3], Jawaban[4]
    public Soal() {
        initComponents();
        labelSoal.setOpaque(false);
        labelSoal.setBackground(new Color(0, 0, 0, 0));
       
        Quiz();
        labelNomor.setText(""+noSoal);
        this.setLocationRelativeTo(null);
    }
   
         
     
    
    public Soal(String nama){
    this.Nama = nama;
    initComponents();
    Quiz();
    labelNomor.setText(""+noSoal);
    this.setLocationRelativeTo(null);
    }
    
    public void Clear(){
      buttonGroup.clearSelection();
    }
    
    public void Done(){
            Hasil hasil = new Hasil(Nama,Benar);
            hasil.setVisible(true);
            this.dispose();
    }
    
    public final void Quiz(){
        Clear();
        if (noSoal == Soal.length-1) {
            btnNext.setText("Selesai");
        }
        if (noSoal < Soal.length) {
        labelSoal.setText(""+Soal[noSoal][0]);
        A.setText(""+Soal[noSoal][1]);
        B.setText(""+Soal[noSoal][2]);
        C.setText(""+Soal[noSoal][3]);
        D.setText(""+Soal[noSoal][4]);
        
        }else{
        Done();
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        btnA = new javax.swing.JToggleButton();
        btnB = new javax.swing.JToggleButton();
        btnC = new javax.swing.JToggleButton();
        btnC1 = new javax.swing.JToggleButton();
        btnNext = new javax.swing.JLabel();
        labelNomor = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        labelSoal = new javax.swing.JLabel();
        bgSoal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A.setText("JAWABAN A");
        A.setAlignmentY(2.0F);
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 260, 70));

        B.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B.setText("JAWABAN B");
        B.setAlignmentY(0.2F);
        B.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMouseClicked(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 260, 70));

        C.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C.setText("JAWABAN C");
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 250, 70));

        D.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D.setText("JAWABAN D");
        D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DMouseClicked(evt);
            }
        });
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 240, 70));

        btnA.setBackground(new java.awt.Color(253, 184, 20));
        buttonGroup.add(btnA);
        btnA.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnA.setText("A");
        btnA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnA.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Chosen.png"))); // NOI18N
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
        });
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 60, 50));

        btnB.setBackground(new java.awt.Color(253, 184, 20));
        buttonGroup.add(btnB);
        btnB.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnB.setText("B");
        btnB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnB.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Chosen.png"))); // NOI18N
        btnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMouseClicked(evt);
            }
        });
        getContentPane().add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 60, 50));

        btnC.setBackground(new java.awt.Color(253, 184, 20));
        buttonGroup.add(btnC);
        btnC.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnC.setText("C");
        btnC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnC.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Chosen.png"))); // NOI18N
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCMouseClicked(evt);
            }
        });
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 60, 50));

        btnC1.setBackground(new java.awt.Color(253, 184, 20));
        buttonGroup.add(btnC1);
        btnC1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnC1.setText("D");
        btnC1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnC1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Chosen.png"))); // NOI18N
        btnC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC1MouseClicked(evt);
            }
        });
        btnC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 60, 50));

        btnNext.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 520, 130, 50));

        labelNomor.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Minus.png"))); // NOI18N
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
        });
        getContentPane().add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        labelSoal.setFont(new java.awt.Font("Kohinoor Devanagari", 3, 16)); // NOI18N
        labelSoal.setText("jLabel1");
        getContentPane().add(labelSoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 890, -1));

        bgSoal.setBackground(new java.awt.Color(253, 184, 19));
        bgSoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AsetProjek/Soal.jpeg"))); // NOI18N
        getContentPane().add(bgSoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        this.setState(Start.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        jawaban = A.getText();
    }//GEN-LAST:event_AMouseClicked

    private void BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseClicked
        jawaban = B.getText();
    }//GEN-LAST:event_BMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
        jawaban = C.getText();
    }//GEN-LAST:event_CMouseClicked

    private void DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DMouseClicked
        jawaban = D.getText();
    }//GEN-LAST:event_DMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
         noSoal+=1;
        if ((Jawaban[noJawaban].equals(jawaban))) {
//            System.out.println(Jawaban[noJawaban]+"=="+(jawaban));
                Benar+=1;
            }else{
                Salah+=1;
            }
        
        noJawaban+=1;
        labelNomor.setText(""+noSoal);
        
        Quiz();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC1MouseClicked
        jawaban = D.getText();
    }//GEN-LAST:event_btnC1MouseClicked

    private void btnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseClicked
        jawaban = C.getText();
    }//GEN-LAST:event_btnCMouseClicked

    private void btnBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMouseClicked
        jawaban = B.getText();
    }//GEN-LAST:event_btnBMouseClicked

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked
        jawaban = A.getText();
    }//GEN-LAST:event_btnAMouseClicked

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel bgSoal;
    private javax.swing.JToggleButton btnA;
    private javax.swing.JToggleButton btnB;
    private javax.swing.JToggleButton btnC;
    private javax.swing.JToggleButton btnC1;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMin;
    private javax.swing.JLabel btnNext;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel labelNomor;
    private javax.swing.JLabel labelSoal;
    // End of variables declaration//GEN-END:variables
}
